<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRiZy5ZI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRiZy5ZI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRiZy5ZI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRiZy5ZI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRiZy5ZI\App_KernelDevDebugContainer([
    'container.build_hash' => 'RiZy5ZI',
    'container.build_id' => '2dbdda3b',
    'container.build_time' => 1635767496,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRiZy5ZI');
